SET search_path TO public;

CREATE TABLE m_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE m_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permission VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE t_url_mappings (
  short_url_path VARCHAR(6) PRIMARY KEY
    CHECK (char_length(short_url_path) = 6),
  original_url VARCHAR(255) NOT NULL,
  created_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(original_url, created_by),
  FOREIGN KEY (created_by) REFERENCES m_users(id) ON DELETE CASCADE
);

INSERT INTO m_permissions (permission) VALUES
  ('CREATE_URL_MAPPING'),
  ('LIST_URL_MAPPING'),
  ('DELETE_URL_MAPPING');
